Update init script with GCP integration

diff --git a/init b/init
--- a/init
+++ b/init
@@ -1,18 +1,38 @@
 #!/bin/bash
 
-export PATH=$PATH:$(pwd)
+INSTALL_FLAG=--i
+GCP_FLAG=--gcp
+HELP_FLAG=--help
 
-source cv_env/bin/activate
+CV_ENV='cv_env'
 
-INSTALL_FLAG=-i
-
-if [[ $# > 1 || ($# == 1 && $1 != $INSTALL_FLAG) ]]
+if [[ $1 == $HELP_FLAG ]]
 then
-	echo "Usage: $(basename $0) [ <$INSTALL_FLAG> ]"
-	exit 1
+	echo "Usage: $(basename $0) [ <$INSTALL_FLAG> <$GCP_FLAG>]"
+	exit 0
 fi
+
+if [ ! -d "./$CV_ENV" ]
+then
+  echo "Virtual environment not found. Installing cv_env."
+  python3 -m venv $CV_ENV
+fi
+
+source $CV_ENV/bin/activate
 
 if [[ $1 == $INSTALL_FLAG ]]; then
 	pip install -r requirements.txt
 fi
 
+
+if [[ $1 == $GCP_FLAG || $2 == $GCP_FLAG ]]; then
+  if ! gsutil version | grep -q 'gsutil version:'; then
+   echo "Installing gsutil"
+   sudo pip install gsutil
+  fi
+  echo "Downloading data from GCP"
+  gsutil cp gs://filter_net/image_data.tar.gz ./image_data.tar.gz
+  echo "Extracting data"
+  mv data data_old
+  tar -xzvf image_data.tar.gz
+fi
